export { default as EditSort } from './EditSort.vue'
export { default as Home } from './Home.vue'
export { default as Login } from './Login.vue'
export { default as MyPage } from './MyPage.vue'
export { default as PlaySortProcess } from './PlaySortProcess.vue'
export { default as PlaySortResult } from './PlaySortResult.vue'
export { default as PlaySortTitle } from './PlaySortTitle.vue'
export { default as RegisterSort } from './RegisterSort.vue'
